port: PORT
baseUrl: BASE_URL # the baseUrl/origin/domain of the bot

# Logging configuration
logging:
  console:
    level: LOG_LEVEL_CONSOLE
  file:
    level: LOG_LEVEL_FILE

# Platforms
facebook:
  verify_token: FB_VERIFY_TOKEN
  page_access_token: FB_PA_TOKEN
  graph_version: FB_GRAPH_VERSION

viber:
  auth_token: VIBER_TOKEN
  name: VIBER_BOT_NAME
  avatar_url: VIBER_BOT_AVATAR_URL

# MongoDB
mongo:
  url: MONGO_URL

# Dialogflow
dialogflow:
  project_id: DF_PROJECT_ID
  private_key: DF_PRIVATE_KEY
  client_email: DF_CLIENT_EMAIL

# Wit.AI
wit:
  token: WIT_TOKEN

# ScraperAPI
scraper:
  api_key: SCRAPER_KEY