port: 3000
baseUrl: # the baseUrl/origin/domain of the bot

# Logging configuration
logging:
  console:
    level: debug
  file:
    level: error
    max_files: 14 # 1 file per day

# Platforms
facebook:
  verify_token: verification_token #Developer Defined token
  page_access_token:
  graph_version:

viber:
  auth_token:
  name:
  avatar_url:
  register_to_events: ['conversation_started', 'subscribed']

# MongoDB
mongo:
  url: mongodb://127.0.0.1:27017/dutybot

# Dialogflow
dialogflow:
  project_id:
  private_key:
  client_email:
  lang: en

# Wit.AI
wit:
  token:

# ScraperAPI
scraper:
  api_key:
