# Logging configuration
logging:
  console:
    level: debug
  file:
    level: error
    max_files: 14 # 1 file per day

# Quotes APIs
quotes:
  favqs:
    token:

# Platforms
facebook:
  verify_token: verification_token #Developer Defined token
  page_access_token:

# MongoDB
mongo:
  url: mongodb://localhost:27017/test
